import localFont from "next/font/local";
import { GlobalProvider } from "@/context/GlobalContext";
import "./globals.css";
import { NotistackProvider } from "@/context/NotistackProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotistackProvider>
          <GlobalProvider>{children}</GlobalProvider>
        </NotistackProvider>
      </body>
    </html>
  );
}
